Rebase code to cdb205ee

diff --git a/builds/any/installer/installer.sh.in b/builds/any/installer/installer.sh.in
--- a/builds/any/installer/installer.sh.in
+++ b/builds/any/installer/installer.sh.in
@@ -141,25 +141,10 @@ if has_boot_env onl_installer_debug; then installer_debug=1; fi
 if test "$installer_debug"; then
   echo "Debug mode"
   set -x
-  installer_wait=30
-else
-  installer_wait=3
 fi
 
 # Pickup ONIE defines for this machine.
-if test "$onie_platform"; then
-  :
-else
-  onie_platform=$(onie-sysinfo -p 2>/dev/null) || :
-fi
-if test "$onie_arch"; then
-  :
-else
-  onie_arch=$(onie-sysinfo -c 2>/dev/null) || :
-fi
-if test "$onie_platform"; then
-  :
-elif test -r /etc/machine.conf; then
+if test -r /etc/machine.conf; then
   . /etc/machine.conf
 fi
 
@@ -257,7 +242,7 @@ if test "${onie_platform}"; then
 
     installer_umount
 
-    if installer_reboot $installer_wait; then
+    if installer_reboot; then
       :
     else
       sync
@@ -267,7 +252,7 @@ if test "${onie_platform}"; then
   }
 else
   if test "$ARCH_X86"; then
-    echo "Missing onie_platform (invalid or missing onie-sysinfo or /etc/machine.conf)" 1>&2
+    echo "Missing onie_platform (invalid /etc/machine.conf)" 1>&2
     exit 1
   fi
   #
@@ -487,11 +472,6 @@ mkdir -p "${rootdir}/etc/onl"
 cp /dev/null "${rootdir}/etc/onl/installer.conf"
 echo "onl_version=\"$onl_version\"" >> "${rootdir}/etc/onl/installer.conf"
 
-# pass in the platform identifier, otherwise encoded in
-# machine-XXX.conf and onie-sysinfo
-echo "onie_platform=$onie_platform" >> "${rootdir}/etc/onl/installer.conf"
-echo "onie_arch=$onie_arch" >> "${rootdir}/etc/onl/installer.conf"
-
 # Generate the MD5 signature for ourselves for future reference.
 installer_md5=$(md5sum "$0" | awk '{print $1}')
 echo "installer_md5=\"$installer_md5\"" >> "${rootdir}/etc/onl/installer.conf"
@@ -548,7 +528,7 @@ installer_force_umount() {
   dev=$1; shift
   mpt=$1; shift
   case "$mpt" in
-    /mnt/*|/boot/*)
+    /mnt/*)
       installer_say "Unmounting $mpt (--force)"
       umount "$mpt"
       ;;
@@ -568,9 +548,6 @@ if test -f preinstall.sh; then
   ./preinstall.sh $rootdir
 fi
 
-# make sure any GPT data is valid and clean
-installer_fixup_gpt || :
-
 chroot "${rootdir}" $installer_shell
 
 if test -f "$postinst"; then
@@ -581,7 +558,7 @@ if test -f "$postinst"; then
 fi
 
 installer_unzip $installer_zip postinstall.sh || :
-if test -f postinstall.sh; then
+if test -f preinstall.sh; then
   chmod +x postinstall.sh
   ./postinstall.sh $rootdir
 fi
@@ -590,7 +567,7 @@ trap - 0 1
 installer_umount
 
 if test "${onie_platform}"; then
-  installer_reboot $installer_wait
+  installer_reboot
 fi
 
 exit
